# RAG Pipeline — Aviation Handbook Assistant

**Graduation Project · Level 2 Summer Training**

This notebook builds the retrieval half of the system, end to end:

| Step | What happens |
|---|---|
| 2.1 | Load the PDFs and inspect what we actually got |
| 2.2 | Split the text into chunks (and justify the strategy) |
| 2.3 | Turn chunks into vectors and store them in ChromaDB |
| 2.4 | Retrieve for a question and build the grounded prompt |
| 2.5 | *(Extended Track only — not part of this Core Track submission)* |
| 2.6 | Evaluate on 14 test questions and write down the failures |
| 2.7 | Export the store so the FastAPI backend loads it directly |

**The one idea behind all of it:** a language model that answers from memory
makes things up. A language model that is handed the *relevant paragraphs* and
told to cite them does not. Everything below exists to find those paragraphs.

---

### Before you run this

```bash
pip install -r ../requirements-notebook.txt
python ../scripts/download_corpus.py
```

Then: **Kernel → Restart & Run All**. It is designed to run top-to-bottom with
no manual steps.

## 0. Configuration

Every tunable value lives here, in one place. Later cells only read these
names — so changing the chunk size means editing one line, not hunting through
the notebook.

In [1]:
from __future__ import annotations

import json
import re
import shutil
import time
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd

# --- Paths ----------------------------------------------------------------
PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
RAW_DIR = PROJECT_ROOT / "data" / "raw"

# We build the Chroma store DIRECTLY where the backend expects it.
VECTOR_STORE_DIR = PROJECT_ROOT / "backend" / "data" / "vector_store"

# --- Chunking -------------------------------------------------------------
CHUNK_SIZE = 1000       # characters, not tokens (see the justification in 2.2)
CHUNK_OVERLAP = 150     # characters repeated between neighbouring chunks
MIN_CHUNK_CHARS = 120   # anything shorter is page furniture, not content

# --- Embeddings & store ---------------------------------------------------
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
COLLECTION_NAME = "faa_handbooks"
EMBED_BATCH_SIZE = 256

# --- Retrieval ------------------------------------------------------------
TOP_K = 5
MIN_SIMILARITY = 0.25   # below this we treat the corpus as having no answer

# --- Generation -----------------------------------------------------------
OLLAMA_MODEL = "llama3.2:3b"
OLLAMA_HOST = "http://localhost:11434"

print("Project root :", PROJECT_ROOT)
print("Raw PDFs     :", RAW_DIR)
print("Vector store :", VECTOR_STORE_DIR)

Project root : C:\Users\Dell\Desktop\ITI final project\ITI final project\rag-assistant-app
Raw PDFs     : C:\Users\Dell\Desktop\ITI final project\ITI final project\rag-assistant-app\data\raw
Vector store : C:\Users\Dell\Desktop\ITI final project\ITI final project\rag-assistant-app\backend\data\vector_store

---
## 2.1 Load & Inspect

Before writing a single line of pipeline code, look at the data. The brief
warns about scanned PDFs that need OCR — this section is how we prove ours are
not.

In [2]:
from pypdf import PdfReader

# Human-readable titles. The filename is what is on disk; the title is what
# gets shown to the user as a citation, so it lives here.
DOCUMENT_TITLES = {
    "phak_pilots_handbook.pdf": "Pilot's Handbook of Aeronautical Knowledge",
    "instrument_flying_handbook.pdf": "Instrument Flying Handbook",
    "weight_and_balance_handbook.pdf": "Aircraft Weight and Balance Handbook",
    "plane_sense_ga_information.pdf": "Plane Sense: General Aviation Information",
    "remote_pilot_suas_study_guide.pdf": "Remote Pilot - Small UAS Study Guide",
}

pdf_paths = sorted(RAW_DIR.glob("*.pdf"))

if not pdf_paths:
    raise FileNotFoundError(
        f"No PDFs found in {RAW_DIR}.\n"
        "Run this first, from the project root:\n"
        "    python scripts/download_corpus.py"
    )

print(f"Found {len(pdf_paths)} PDF(s):\n")
for path in pdf_paths:
    size_mb = path.stat().st_size / (1024 * 1024)
    print(f"  {path.name:<40} {size_mb:>7.1f} MB")

Found 5 PDF(s):

  instrument_flying_handbook.pdf              65.2 MB
  phak_pilots_handbook.pdf                    53.5 MB
  plane_sense_ga_information.pdf              14.8 MB
  remote_pilot_suas_study_guide.pdf            6.4 MB
  weight_and_balance_handbook.pdf             14.2 MB

In [3]:
def load_pdf(path: Path) -> dict:
    """
    Read one PDF into a list of per-page strings.

    We keep pages separate (rather than concatenating the whole book) because
    the page number is the single most useful thing in a citation - it is what
    lets a human open the handbook and check the answer.
    """
    title = DOCUMENT_TITLES.get(path.name, path.stem.replace("_", " ").title())
    record = {
        "filename": path.name,
        "title": title,
        "pages": [],
        "empty_pages": 0,
        "error": None,
    }

    try:
        reader = PdfReader(str(path))
        for page_number, page in enumerate(reader.pages, start=1):
            try:
                text = page.extract_text() or ""
            except Exception:
                text = ""          # a single bad page must not kill the book
            if not text.strip():
                record["empty_pages"] += 1
            record["pages"].append({"page": page_number, "text": text})
    except Exception as exc:
        record["error"] = f"{exc.__class__.__name__}: {exc}"

    return record


documents = []
for path in pdf_paths:
    print(f"Parsing {path.name} ...", end=" ", flush=True)
    started = time.perf_counter()
    doc = load_pdf(path)
    documents.append(doc)
    print(f"{len(doc['pages'])} pages in {time.perf_counter() - started:.1f}s")

Parsing instrument_flying_handbook.pdf ...

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54726, 0, 2633565846704), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [202, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 322, 260, 0, 0, 0, 555, 0, 0, 0, 0, 0, 555, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 527, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 528, 0, 585, 0, 274, 0, 0, 0, 0, 0, 0, 0, 0, 380, 0, 0, 583]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54724, 0, 2633565846704), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [182, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 211, 0, 211, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 465, 0, 0, 233, 0, 0, 0, 0, 0, 0, 0, 0, 523, 0, 0, 0, 539, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 522, 0, 423, 525, 453, 0, 0, 534, 229, 0, 0, 229, 0, 534, 522, 0, 0, 318, 373, 313, 526, 0, 707, 0, 441]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54726, 0, 2633565846704), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [202, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 322, 260, 0, 0, 0, 0, 555, 0, 0, 0, 0, 555, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 527, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 528, 0, 585, 0, 274, 0, 0, 0, 0, 0, 0, 0, 0, 380, 0, 0, 583]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54724, 0, 2633565846704), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [182, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 211, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 470, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 522, 0, 0, 525, 453, 0, 524, 0, 229, 0, 0, 229, 0, 534, 522, 527, 0, 318, 0, 313, 526]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54726, 0, 2633565846704), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [202, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 322, 260, 0, 0, 0, 0, 0, 555, 0, 0, 0, 555, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 527, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 598, 0, 0, 528, 0, 585, 0, 274, 0, 0, 0, 0, 0, 0, 0, 0, 380, 0, 0, 583]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54724, 0, 2633565846704), '/LastChar': 119, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [182, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 211, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 442, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 522, 0, 423, 525, 453, 283, 524, 534, 229, 0, 0, 229, 808, 534, 522, 0, 0, 318, 0, 313, 526, 0, 707]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54726, 0, 2633565846704), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [202, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 322, 260, 0, 0, 0, 0, 0, 555, 0, 0, 0, 555, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 527, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 528, 0, 0, 0, 528, 0, 585, 0, 274, 0, 0, 0, 0, 0, 0, 0, 0, 380, 0, 0, 583]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54724, 0, 2633565846704), '/LastChar': 119, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [182, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 211, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 442, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 522, 0, 423, 525, 453, 283, 524, 534, 229, 0, 0, 229, 808, 534, 522, 0, 0, 318, 0, 313, 526, 0, 707]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/UMPTKK+Helvetica-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(15297, 0, 2633565846704), '/LastChar': 116, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [278, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 722, 0, 0, 0, 0, 0, 0, 0, 667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 556, 0, 0, 611, 556, 0, 611, 0, 278, 0, 0, 278, 0, 611, 611, 0, 0, 389, 0, 333]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/UMPTKK+Helvetica-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(15297, 0, 2633565846704), '/LastChar': 109, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [278, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 278, 0, 556, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 722, 0, 0, 0, 667, 0, 0, 0, 0, 0, 0, 0, 833, 722, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 556, 0, 0, 0, 556, 0, 0, 0, 0, 0, 0, 0, 889]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/TIFNWM+LetterGothic-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54769, 0, 2633565846704), '/LastChar': 176, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 307, 207, 0, 513, 513, 513, 513, 513, 513, 513, 513, 513, 513, 207, 0, 0, 0, 0, 0, 0, 612, 0, 580, 666, 0, 0, 646, 0, 239, 0, 542, 472, 804, 658, 689, 532, 0, 538, 493, 497, 0, 558, 846, 571, 0, 0, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 318]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/RFGBUQ+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54767, 0, 2633565846704), '/LastChar': 118, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 307, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 666, 0, 487, 0, 0, 0, 0, 0, 0, 804, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 0, 0, 564, 501, 292, 559, 0, 234, 0, 0, 0, 834, 555, 549, 569, 0, 327, 0, 331, 0, 481]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/QGRVGS+ArialMT', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(15312, 0, 2633565846704), '/LastChar': 188, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [278, 0, 355, 0, 0, 0, 0, 191, 333, 333, 0, 0, 278, 333, 278, 278, 556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 278, 278, 0, 0, 0, 0, 0, 667, 667, 722, 722, 667, 611, 778, 722, 278, 500, 667, 556, 833, 722, 778, 667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 0, 0, 0, 0, 0, 0, 556, 556, 500, 556, 556, 278, 556, 556, 222, 0, 500, 222, 833, 556, 556, 556, 0, 333, 500, 278, 556, 500, 722, 500, 500, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 400, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 834]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/PCCPSU+Arial-BoldMT', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(15313, 0, 2633565846704), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [278, 0, 0, 0, 0, 0, 0, 0, 333, 333, 0, 0, 278, 333, 0, 0, 556, 556, 556, 556, 0, 556, 0, 556, 556, 0, 0, 0, 0, 0, 0, 0, 0, 722, 722, 722, 722, 667, 611, 0, 0, 278, 0, 722, 611, 833, 722, 778, 667, 0, 722, 667, 611, 722, 667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 556, 0, 0, 0, 778, 0, 556]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54724, 0, 2633565846704), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [182, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 507, 0, 0, 0, 474, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 423, 525, 453, 0, 0, 0, 0, 0, 0, 0, 0, 534, 522, 0, 0, 318, 373, 0, 526]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54724, 0, 2633565846704), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [182, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 627, 0, 0, 0, 442, 0, 0, 0, 507, 0, 0, 0, 474, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 423, 525, 453, 283, 524, 0, 229, 0, 0, 229, 0, 534, 522, 0, 0, 318, 0, 0, 526]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54724, 0, 2633565846704), '/LastChar': 116, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [182, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 647, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 474, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 522, 0, 0, 525, 453, 0, 0, 534, 0, 0, 0, 0, 0, 534, 522, 527, 0, 318, 0, 313]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/RFGBUQ+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54767, 0, 2633565846704), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 646, 0, 239, 0, 0, 472, 0, 0, 0, 0, 0, 0, 493, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 0, 448, 564, 501, 292, 559, 0, 234, 0, 469, 234, 834, 555, 549, 569, 0, 327, 396, 331, 551]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54724, 0, 2633565846704), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [182, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 568, 0, 555, 0, 0, 465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 507, 0, 0, 0, 0, 0, 539, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 522, 0, 423, 0, 453, 283, 524, 534, 229, 0, 0, 229, 808, 534, 522, 527, 0, 318, 373, 313, 526]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/RFGBUQ+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54767, 0, 2633565846704), '/LastChar': 90, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 513, 513, 513, 513, 513, 513, 513, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 652, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 571, 541, 553]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54726, 0, 2633565846704), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [202, 0, 0, 0, 0, 0, 0, 0, 314, 314, 0, 0, 0, 322, 260, 0, 0, 0, 0, 0, 0, 555, 0, 0, 0, 555, 0, 0, 0, 0, 0, 0, 0, 0, 0, 595, 0, 0, 527, 0, 0, 0, 0, 0, 0, 846, 0, 0, 581, 0, 0, 0, 548, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 528, 0, 451, 596, 528, 0, 585, 586, 274, 0, 0, 274, 0, 586, 577, 598, 0, 380, 434, 367, 583, 0, 0, 0, 523]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KKRQAE+Myriad-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54724, 0, 2633565846704), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [182, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 211, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 623, 0, 0, 0, 0, 0, 0, 0, 0, 507, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 522, 0, 423, 525, 453, 0, 0, 534, 229, 0, 0, 0, 0, 534, 522, 0, 0, 318, 0, 313, 526]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/RFGBUQ+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54767, 0, 2633565846704), '/LastChar': 114, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 327]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/RFGBUQ+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54767, 0, 2633565846704), '/LastChar': 82, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 538]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/RFGBUQ+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54767, 0, 2633565846704), '/LastChar': 113, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 563]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/RFGBUQ+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54767, 0, 2633565846704), '/LastChar': 81, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 689]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/RFGBUQ+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54767, 0, 2633565846704), '/LastChar': 112, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 569]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/RFGBUQ+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54767, 0, 2633565846704), '/LastChar': 80, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 532]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/RFGBUQ+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(54767, 0, 2633565846704), '/LastChar': 111, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 549]}, but is not installed. Consider installing fontTools if you encounter encoding problems.

371 pages in 152.1s
Parsing phak_pilots_handbook.pdf ...

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 65, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 84, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [612, 0, 0, 0, 492, 0, 0, 0, 0, 0, 0, 472, 0, 0, 0, 0, 0, 538, 493, 497]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 0, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 0, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 0, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 122, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471, 428]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 122, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 553, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471, 428]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 122, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 0, 553, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471, 428]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 122, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 541, 553, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 0, 471, 428]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ZMGGBV+Myriad-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(28755, 0, 2633857606496), '/LastChar': 122, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 0, 513, 513, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 612, 542, 580, 666, 492, 487, 646, 0, 239, 370, 542, 472, 804, 658, 689, 532, 689, 538, 493, 497, 647, 558, 846, 0, 541, 553, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 292, 559, 555, 234, 243, 469, 0, 834, 555, 549, 569, 563, 327, 396, 331, 551, 481, 736, 463, 471, 428]}, but is not installed. Consider installing fontTools if you encounter encoding problems.

524 pages in 148.7s
Parsing plane_sense_ga_information.pdf ...

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1464, 0, 2633735635360), '/LastChar': 87, '/Widths': [250, 0, 0, 0, 0, 0, 0, 0, 333, 333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 333, 0, 0, 0, 0, 0, 0, 722, 0, 722, 722, 667, 611, 778, 778, 389, 0, 0, 0, 944, 722, 778, 0, 778, 722, 556, 667, 722, 0, 1000], '/BaseFont': '/KCTSQO+TimesNewRomanPS-BoldMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1470, 0, 2633735635360), '/LastChar': 122, '/Widths': [250, 0, 0, 0, 0, 0, 0, 0, 333, 333, 0, 0, 250, 333, 250, 278, 500, 500, 0, 0, 500, 500, 0, 500, 0, 0, 278, 0, 0, 0, 0, 0, 0, 722, 667, 667, 722, 611, 556, 722, 722, 333, 0, 0, 0, 889, 722, 722, 556, 0, 667, 556, 611, 722, 0, 0, 0, 722, 611, 0, 0, 0, 0, 0, 0, 444, 500, 444, 500, 444, 333, 500, 500, 278, 0, 0, 278, 778, 500, 500, 500, 0, 333, 389, 278, 500, 500, 722, 500, 500, 444], '/BaseFont': '/KCTSQO+TimesNewRomanPSMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(132, 0, 2633735635360), '/LastChar': 116, '/Widths': [250, 0, 0, 0, 0, 0, 0, 0, 333, 333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 500, 0, 278, 0, 0, 278, 0, 0, 278, 0, 0, 500, 0, 0, 389, 389, 278], '/BaseFont': '/VDGBOS+TimesNewRomanPS-ItalicMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1509, 0, 2633735635360), '/LastChar': 167, '/Widths': [278, 0, 0, 0, 0, 0, 0, 191, 333, 333, 0, 0, 278, 333, 278, 278, 556, 556, 556, 556, 556, 556, 556, 556, 0, 556, 278, 0, 0, 0, 0, 0, 0, 667, 667, 722, 722, 667, 611, 0, 0, 278, 0, 667, 556, 833, 722, 778, 667, 0, 722, 667, 611, 722, 0, 944, 0, 667, 611, 0, 0, 0, 0, 0, 0, 556, 556, 500, 556, 556, 278, 556, 556, 222, 222, 500, 222, 833, 556, 556, 556, 556, 333, 500, 278, 556, 500, 722, 500, 500, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 556], '/BaseFont': '/QGRXWC+ArialMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1512, 0, 2633735635360), '/LastChar': 121, '/Widths': [278, 0, 0, 0, 0, 0, 0, 0, 333, 333, 0, 0, 278, 0, 278, 0, 0, 556, 556, 556, 556, 556, 556, 556, 0, 0, 0, 0, 0, 0, 0, 0, 0, 722, 0, 722, 722, 667, 611, 0, 0, 278, 556, 0, 611, 833, 722, 778, 667, 0, 722, 667, 611, 722, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 556, 0, 556, 611, 556, 333, 0, 0, 278, 0, 0, 278, 889, 611, 611, 611, 0, 389, 556, 333, 611, 556, 778, 0, 556], '/BaseFont': '/QGRXWC+Arial-BoldMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1515, 0, 2633735635360), '/LastChar': 121, '/Widths': [278, 0, 0, 0, 0, 0, 0, 0, 333, 333, 0, 0, 0, 0, 0, 0, 0, 556, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 667, 0, 0, 0, 0, 0, 0, 0, 278, 0, 0, 0, 0, 0, 0, 0, 0, 0, 667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 556, 556, 500, 556, 556, 278, 556, 556, 222, 0, 0, 0, 833, 556, 556, 556, 0, 333, 500, 278, 0, 500, 722, 0, 500], '/BaseFont': '/QGRXWC+Arial-ItalicMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1512, 0, 2633735635360), '/LastChar': 116, '/Widths': [278, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 278, 0, 0, 0, 0, 556, 0, 0, 0, 556, 556, 0, 0, 0, 0, 0, 0, 0, 0, 722, 0, 722, 722, 667, 611, 0, 0, 278, 0, 0, 0, 0, 722, 778, 0, 0, 0, 0, 611, 0, 0, 944, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 556, 611, 556, 333, 0, 611, 278, 0, 556, 278, 889, 611, 611, 611, 0, 389, 556, 333], '/BaseFont': '/QGRXWC+Arial-BoldMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1515, 0, 2633735635360), '/LastChar': 121, '/Widths': [278, 0, 0, 0, 0, 0, 0, 0, 333, 333, 0, 0, 278, 0, 278, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 667, 0, 0, 0, 0, 0, 0, 0, 278, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 944, 0, 0, 0, 0, 0, 0, 0, 0, 0, 556, 556, 500, 556, 556, 278, 556, 556, 222, 0, 500, 222, 833, 556, 556, 556, 556, 333, 500, 278, 556, 500, 722, 0, 500], '/BaseFont': '/QGRXWC+Arial-ItalicMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1509, 0, 2633735635360), '/LastChar': 121, '/Widths': [278, 0, 0, 0, 0, 0, 0, 0, 333, 333, 0, 0, 0, 333, 0, 0, 556, 556, 0, 0, 0, 0, 556, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 667, 0, 0, 722, 0, 0, 0, 0, 0, 0, 0, 0, 833, 722, 0, 0, 0, 722, 667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 556, 0, 500, 556, 556, 0, 556, 556, 222, 0, 500, 222, 0, 556, 556, 0, 0, 333, 500, 278, 0, 0, 0, 0, 500], '/BaseFont': '/QGRXWC+ArialMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1470, 0, 2633735635360), '/LastChar': 121, '/Widths': [250, 0, 0, 0, 0, 0, 0, 0, 333, 333, 0, 0, 250, 333, 250, 278, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 0, 0, 0, 0, 0, 0, 0, 722, 667, 667, 722, 611, 0, 722, 722, 333, 0, 0, 611, 889, 722, 722, 556, 0, 667, 556, 611, 0, 722, 944, 0, 0, 0, 0, 0, 0, 0, 0, 0, 444, 500, 444, 500, 444, 333, 500, 500, 278, 278, 500, 278, 778, 500, 500, 500, 500, 333, 389, 278, 500, 500, 722, 500, 500], '/BaseFont': '/KCTSQO+TimesNewRomanPSMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1464, 0, 2633735635360), '/LastChar': 146, '/Widths': [250, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 250, 333, 250, 278, 500, 500, 500, 0, 0, 500, 500, 0, 500, 0, 333, 0, 0, 0, 0, 0, 0, 722, 667, 722, 722, 667, 611, 778, 778, 389, 0, 0, 0, 944, 722, 778, 0, 0, 722, 556, 667, 0, 722, 1000, 0, 722, 0, 0, 0, 0, 0, 0, 0, 500, 0, 444, 556, 444, 333, 500, 556, 278, 0, 556, 278, 833, 556, 500, 556, 556, 444, 389, 333, 556, 500, 722, 500, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 333], '/BaseFont': '/KCTSQO+TimesNewRomanPS-BoldMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1149, 0, 2633735635360), '/LastChar': 118, '/Widths': [313, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 303, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 600, 0, 601, 678, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 557, 0, 0, 0, 902, 0, 0, 0, 0, 0, 0, 0, 0, 0, 525, 0, 461, 0, 526, 318, 553, 558, 229, 0, 0, 0, 0, 558, 543, 0, 0, 360, 446, 334, 0, 498], '/BaseFont': '/QGRXWC+Tahoma', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1509, 0, 2633735635360), '/LastChar': 116, '/Widths': [278, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 278, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 722, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 667, 611, 722, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 556, 0, 0, 0, 556, 278, 0, 0, 222, 0, 0, 0, 833, 556, 556, 556, 0, 333, 500, 278], '/BaseFont': '/QGRXWC+ArialMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1512, 0, 2633735635360), '/LastChar': 118, '/Widths': [278, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 722, 0, 0, 0, 0, 611, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 556, 0, 0, 611, 556, 0, 0, 0, 278, 0, 0, 278, 889, 611, 611, 0, 0, 389, 556, 333, 0, 556], '/BaseFont': '/QGRXWC+Arial-BoldMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1512, 0, 2633735635360), '/LastChar': 89, '/Widths': [278, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 722, 0, 722, 722, 667, 0, 0, 0, 278, 0, 0, 611, 833, 722, 778, 0, 0, 722, 667, 611, 722, 667, 0, 0, 667], '/BaseFont': '/QGRXWC+Arial-BoldMT', '/FirstChar': 32, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1470, 0, 2633735635360), '/LastChar': 65, '/Widths': [333, 0, 0, 0, 500, 0, 500, 500, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 722], '/BaseFont': '/KCTSQO+TimesNewRomanPSMT', '/FirstChar': 45, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Subtype': '/Type1', '/FontDescriptor': IndirectObject(1464, 0, 2633735635360), '/LastChar': 89, '/Widths': [722, 667, 0, 0, 667, 0, 0, 0, 0, 500, 0, 667, 944, 722, 0, 0, 0, 722, 0, 667, 722, 0, 0, 0, 722], '/BaseFont': '/KCTSQO+TimesNewRomanPS-BoldMT', '/FirstChar': 65, '/Encoding': '/WinAnsiEncoding', '/Type': '/Font'}, but is not installed. Consider installing fontTools if you encounter encoding problems.

100 pages in 27.3s
Parsing remote_pilot_suas_study_guide.pdf ... 88 pages in 3.6s
Parsing weight_and_balance_handbook.pdf ...

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/QSEAVR+Swiss721BT-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3316, 0, 2633813395552), '/LastChar': 119, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [284, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 334, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 741, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 551, 615, 570, 324, 0, 0, 0, 0, 0, 0, 0, 597, 608, 613, 0, 384, 546, 0, 597, 0, 765]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/HCOYZJ+Swiss721BT-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3494, 0, 2633813395552), '/LastChar': 116, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [274, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 662, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 646, 0, 0, 0, 904, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 547, 264, 595, 569, 222, 0, 0, 0, 0, 0, 581, 0, 0, 332, 0, 281]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/HCOYZJ+Swiss721BT-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3494, 0, 2633813395552), '/LastChar': 116, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [274, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 637, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 646, 0, 0, 0, 904, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 547, 264, 595, 569, 222, 0, 0, 0, 0, 0, 0, 0, 0, 332, 0, 281]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/HCOYZJ+Swiss721BT-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3494, 0, 2633813395552), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [274, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 543, 0, 525, 594, 547, 0, 0, 569, 0, 0, 0, 0, 0, 0, 581, 0, 0, 332, 0, 281, 569]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KRALPD+Swiss721BT-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3592, 0, 2633813395552), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [274, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 637, 0, 713, 707, 639, 0, 0, 0, 0, 0, 0, 535, 830, 0, 0, 0, 0, 0, 0, 571, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 543, 0, 525, 594, 547, 0, 595, 569, 222, 0, 0, 226, 858, 569, 581, 0, 0, 332, 0, 281, 569, 0, 0, 0, 507]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/JSQFBF+Swiss721BT-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 65, '/FontDescriptor': IndirectObject(2345, 0, 2633813395552), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [637, 0, 713, 707, 639, 0, 0, 0, 0, 0, 0, 535, 830, 0, 0, 0, 0, 0, 0, 571, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 543, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 858, 0, 0, 0, 0, 0, 0, 281, 569]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/HPMTZJ+MyriadPro-Regular', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(2399, 0, 2633813395552), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 487, 0, 652, 0, 0, 542, 0, 0, 0, 0, 0, 0, 538, 0, 0, 647, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 482, 569, 448, 564, 501, 0, 559, 555, 234, 243, 469, 236, 834, 555, 549, 569, 0, 327, 396, 331, 551]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ACADFX+Swiss721BT-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3643, 0, 2633813395552), '/LastChar': 120, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [284, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 567, 567, 0, 0, 0, 0, 567, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 562, 613, 0, 0, 0, 0, 0, 0, 0, 0, 0, 275, 877, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 516]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KRALPD+Swiss721BT-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3592, 0, 2633813395552), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [274, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 833, 0, 0, 274, 0, 0, 549, 0, 549, 549, 0, 549, 549, 0, 549, 0, 0, 0, 0, 0, 0, 0, 637, 662, 713, 707, 639, 583, 0, 0, 0, 0, 0, 535, 830, 0, 0, 0, 0, 664, 0, 571, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 543, 0, 525, 594, 547, 0, 595, 569, 222, 0, 0, 226, 858, 569, 581, 0, 0, 332, 496, 281, 569, 0, 0, 0, 507]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ACADFX+Swiss721BT-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3643, 0, 2633813395552), '/LastChar': 120, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [284, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 284, 0, 567, 567, 0, 567, 0, 0, 567, 0, 567, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 744, 0, 653, 0, 777, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 934, 0, 0, 0, 0, 0, 0, 0, 0, 0, 562, 613, 0, 0, 570, 0, 610, 0, 0, 0, 0, 275, 877, 0, 0, 0, 0, 0, 546, 0, 597, 0, 0, 516]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/HCOYZJ+Swiss721BT-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3494, 0, 2633813395552), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [274, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 713, 0, 0, 0, 764, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 543, 0, 525, 594, 547, 0, 0, 569, 222, 0, 0, 226, 858, 0, 581, 0, 0, 332, 496, 281, 569]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KRALPD+Swiss721BT-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3592, 0, 2633813395552), '/LastChar': 148, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [274, 0, 0, 0, 0, 0, 683, 0, 336, 336, 0, 833, 0, 0, 274, 301, 549, 549, 549, 549, 549, 549, 549, 549, 549, 549, 0, 0, 0, 0, 0, 0, 0, 637, 662, 713, 707, 639, 583, 0, 0, 0, 0, 0, 535, 830, 0, 0, 630, 0, 664, 0, 571, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 543, 594, 525, 594, 547, 264, 595, 569, 222, 0, 0, 226, 858, 569, 581, 594, 0, 332, 496, 281, 569, 0, 728, 479, 507, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 413, 413]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/QSEAVR+Swiss721BT-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3316, 0, 2633813395552), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [284, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 334, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 744, 0, 0, 0, 0, 0, 0, 0, 0, 0, 872, 741, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 562, 0, 551, 615, 570, 324, 610, 0, 272, 0, 0, 275, 877, 597, 608, 613, 0, 384, 546, 318, 597, 530, 765, 0, 537]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/HCOYZJ+Swiss721BT-Roman', '/Encoding': IndirectObject(3680, 0, 2633813395552), '/FirstChar': 31, '/FontDescriptor': IndirectObject(3494, 0, 2633813395552), '/LastChar': 122, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [833, 274, 0, 0, 0, 0, 845, 0, 0, 336, 336, 0, 833, 274, 312, 274, 0, 549, 549, 549, 549, 549, 549, 549, 549, 549, 549, 297, 0, 0, 0, 0, 0, 0, 637, 0, 0, 0, 0, 583, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 646, 0, 709, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 543, 594, 525, 594, 547, 264, 595, 569, 222, 0, 517, 226, 858, 569, 581, 594, 594, 332, 496, 281, 569, 481, 728, 0, 507, 481]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/QSEAVR+Swiss721BT-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3316, 0, 2633813395552), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [284, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 334, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 704, 744, 727, 653, 598, 777, 0, 0, 0, 0, 0, 872, 741, 789, 0, 0, 714, 667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 562, 0, 551, 615, 570, 324, 610, 0, 272, 0, 0, 275, 877, 597, 608, 613, 0, 384, 546, 318, 597, 530, 765, 0, 537]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KRALPD+Swiss721BT-Roman', '/Encoding': IndirectObject(3680, 0, 2633813395552), '/FirstChar': 31, '/FontDescriptor': IndirectObject(3592, 0, 2633813395552), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [833, 274, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 833, 0, 0, 274, 0, 549, 549, 549, 549, 549, 549, 549, 549, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 707, 0, 583, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 543, 594, 0, 594, 547, 0, 595, 0, 222, 0, 0, 226, 858, 569, 581, 0, 0, 332, 496, 281, 569]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ACADFX+Swiss721BT-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3643, 0, 2633813395552), '/LastChar': 120, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [284, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 284, 0, 567, 567, 567, 567, 0, 567, 567, 0, 567, 0, 0, 0, 0, 833, 0, 0, 0, 686, 0, 744, 0, 653, 0, 777, 0, 0, 0, 0, 0, 872, 0, 0, 0, 0, 0, 0, 0, 0, 0, 934, 0, 0, 0, 0, 0, 0, 0, 0, 0, 562, 613, 0, 0, 570, 0, 610, 0, 272, 0, 0, 275, 877, 0, 0, 0, 0, 0, 546, 318, 597, 0, 0, 516]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/OKBJTV+Swiss721BT-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3686, 0, 2633813395552), '/LastChar': 120, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [212, 0, 0, 0, 0, 0, 0, 0, 284, 284, 0, 0, 207, 0, 207, 343, 513, 513, 0, 513, 0, 0, 0, 0, 0, 513, 0, 0, 0, 0, 0, 0, 0, 0, 542, 0, 666, 0, 487, 0, 0, 239, 0, 0, 472, 804, 658, 0, 532, 0, 538, 493, 0, 0, 0, 846, 0, 0, 0, 0, 0, 0, 0, 500, 0, 482, 569, 448, 564, 501, 0, 559, 555, 234, 0, 0, 236, 834, 555, 549, 0, 0, 327, 396, 331, 551, 0, 0, 463]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/NGMDFX+Swiss721BT-Roman', '/Encoding': IndirectObject(2494, 0, 2633813395552), '/FirstChar': 1, '/FontDescriptor': IndirectObject(2495, 0, 2633813395552), '/LastChar': 173, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [292, 553, 284, 207, 463, 513, 284, 542, 513, 538, 551, 549, 487, 555, 559, 736, 471, 331, 834, 448, 396, 569, 212, 501, 555, 482, 236, 569, 327, 234, 612, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 564, 497, 513, 513, 513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 207, 0, 513, 415, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 472, 0, 0, 469, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 583]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ACADFX+Swiss721BT-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3643, 0, 2633813395552), '/LastChar': 120, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [284, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 833, 0, 0, 284, 317, 567, 567, 567, 567, 567, 567, 567, 0, 567, 0, 0, 0, 0, 833, 0, 0, 0, 686, 0, 744, 0, 653, 598, 777, 0, 0, 0, 0, 0, 872, 0, 789, 0, 0, 714, 0, 0, 0, 0, 934, 0, 0, 0, 0, 0, 0, 0, 0, 0, 562, 613, 551, 0, 570, 0, 610, 602, 272, 0, 0, 275, 877, 597, 608, 613, 0, 384, 546, 318, 597, 0, 765, 516]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KRALPD+Swiss721BT-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3592, 0, 2633813395552), '/LastChar': 148, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [274, 0, 0, 0, 0, 0, 683, 0, 336, 336, 0, 833, 0, 0, 274, 301, 549, 549, 549, 549, 549, 549, 549, 549, 549, 549, 0, 0, 0, 0, 0, 0, 0, 637, 662, 713, 707, 639, 583, 0, 0, 0, 0, 0, 535, 830, 0, 0, 630, 0, 664, 0, 571, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 543, 594, 525, 594, 547, 264, 595, 569, 222, 0, 0, 226, 858, 569, 581, 594, 0, 332, 496, 281, 569, 0, 728, 479, 507, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 413, 413]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/QSEAVR+Swiss721BT-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3316, 0, 2633813395552), '/LastChar': 121, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [284, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 833, 0, 334, 0, 317, 567, 567, 0, 0, 0, 0, 567, 567, 0, 0, 0, 0, 0, 0, 0, 0, 0, 686, 704, 744, 727, 653, 598, 777, 0, 0, 0, 0, 0, 872, 741, 789, 0, 0, 714, 667, 0, 0, 0, 934, 0, 0, 0, 0, 0, 0, 0, 0, 0, 562, 0, 551, 615, 570, 324, 610, 602, 272, 0, 0, 275, 877, 597, 608, 613, 0, 384, 546, 318, 597, 530, 765, 0, 537]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/HCOYZJ+Swiss721BT-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3494, 0, 2633813395552), '/LastChar': 117, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [274, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 549, 549, 549, 549, 549, 549, 549, 549, 549, 549, 0, 0, 0, 0, 0, 0, 0, 0, 0, 713, 0, 0, 0, 764, 0, 0, 0, 0, 0, 0, 0, 0, 0, 773, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 543, 0, 525, 594, 547, 0, 0, 569, 222, 0, 0, 226, 858, 0, 581, 0, 0, 332, 496, 281, 569]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/ACADFX+Swiss721BT-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3643, 0, 2633813395552), '/LastChar': 150, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [284, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 833, 0, 0, 284, 317, 567, 567, 567, 567, 567, 567, 567, 567, 567, 0, 0, 0, 0, 833, 0, 0, 0, 686, 0, 744, 0, 653, 598, 777, 0, 0, 0, 0, 0, 872, 0, 789, 667, 0, 714, 0, 0, 717, 0, 934, 0, 0, 0, 0, 0, 0, 0, 0, 0, 562, 613, 551, 615, 570, 0, 610, 602, 272, 0, 0, 275, 877, 597, 608, 613, 0, 384, 546, 318, 597, 0, 765, 516, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 500]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KRALPD+Swiss721BT-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3592, 0, 2633813395552), '/LastChar': 148, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [274, 0, 0, 0, 0, 0, 683, 0, 336, 336, 0, 833, 0, 0, 274, 301, 549, 549, 549, 549, 549, 549, 549, 549, 549, 549, 0, 0, 0, 0, 0, 0, 0, 637, 662, 713, 707, 639, 583, 0, 0, 0, 0, 0, 535, 830, 0, 0, 630, 0, 664, 0, 571, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 543, 594, 525, 594, 547, 264, 595, 569, 222, 0, 0, 226, 858, 569, 581, 594, 0, 332, 496, 281, 569, 0, 728, 479, 507, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 413, 413]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/KRALPD+Swiss721BT-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(3592, 0, 2633813395552), '/LastChar': 148, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [274, 0, 0, 0, 0, 0, 683, 0, 336, 336, 0, 833, 274, 0, 274, 301, 549, 549, 549, 549, 549, 549, 549, 549, 549, 549, 0, 0, 0, 0, 0, 0, 0, 637, 662, 713, 707, 639, 583, 0, 0, 0, 0, 0, 535, 830, 0, 0, 630, 0, 664, 0, 571, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 543, 594, 525, 594, 547, 264, 595, 569, 222, 0, 0, 226, 858, 569, 581, 594, 0, 332, 496, 281, 569, 0, 728, 479, 507, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 413, 413]}, but is not installed. Consider installing fontTools if you encounter encoding problems.

114 pages in 10.6s

### What did we actually get?

The table below is the answer to the brief's question: *how many documents and
pages? what formats? which files failed to parse or need OCR?*

The column that matters is **`empty_pages_pct`**. A text-based PDF returns text
for nearly every page. A **scanned** PDF returns nothing, because the page is
just a photograph — that is the OCR trap. Anything above ~30% would need OCR
(e.g. `pytesseract`) before it is usable.

In [4]:
inspection = pd.DataFrame([
    {
        "document": doc["title"],
        "file": doc["filename"],
        "pages": len(doc["pages"]),
        "empty_pages": doc["empty_pages"],
        "empty_pages_pct": round(100 * doc["empty_pages"] / max(len(doc["pages"]), 1), 1),
        "total_chars": sum(len(p["text"]) for p in doc["pages"]),
        "avg_chars_per_page": int(
            np.mean([len(p["text"]) for p in doc["pages"]]) if doc["pages"] else 0
        ),
        "parse_error": doc["error"] or "-",
    }
    for doc in documents
])

display(inspection)

print(f"\nCorpus totals: {inspection['pages'].sum():,} pages, "
      f"{inspection['total_chars'].sum():,} characters")

needs_ocr = inspection[inspection["empty_pages_pct"] > 30]
if len(needs_ocr):
    print("\n WARNING - these look scanned and would need OCR:")
    print(needs_ocr[["document", "empty_pages_pct"]].to_string(index=False))
else:
    print("\nAll documents have an extractable text layer. No OCR needed.")

,document,file,pages,empty_pages,empty_pages_pct,total_chars,avg_chars_per_page,parse_error
0,Instrument Flying Handbook,instrument_flying_handbook.pdf,371,1,0.3,1141610,3077,-
1,Pilot's Handbook of Aeronautical Knowledge,phak_pilots_handbook.pdf,524,1,0.2,1873275,3574,-
2,Plane Sense: General Aviation Information,plane_sense_ga_information.pdf,100,3,3.0,164378,1643,-
3,Remote Pilot - Small UAS Study Guide,remote_pilot_suas_study_guide.pdf,88,0,0.0,168409,1913,-
4,Aircraft Weight and Balance Handbook,weight_and_balance_handbook.pdf,114,2,1.8,264461,2319,-

Corpus totals: 1,197 pages, 3,612,133 characters

All documents have an extractable text layer. No OCR needed.

### Eyeballing the raw text

Statistics can hide problems. Here is a real page, unedited — this is where you
see the mess that Section 2.2 has to clean up.

In [5]:
sample = documents[0]["pages"][80]
print(f"--- {documents[0]['title']}, page {sample['page']} (raw) ---\n")
print(sample["text"][:900])

--- Instrument Flying Handbook, page 81 (raw) ---

4-4
Outside
force
Net
forces
Path
Apply down
elevator
Path
Net forces
Figure 4-4. Newton’s First Law of Motion: the Law of Inertia.
Time
2,000 lb300 hp
2,000 lb150 hp
= Acceleration Force
Mass
Figure 4-5. Newton’s Second Law of Motion: the Law of Momentum.
• Form Drag
Form drag is the drag created because of the shape of a
component or the aircraft. If one were to place a circular
disk in an air stream, the pressure on both the top and bottom
would be equal. However, the airflow starts to break down
as the air flows around the back of the disk. This creates
turbulence and hence a lower pressure results. Because the
total pressure is affected by this reduced pressure, it creates
a drag. Newer aircraft are generally made with consideration
to this by fairing parts along the fuselage (teardrop) so that
turbulence and form drag is reduced.
Total lift must overcome the total w

**Problems visible in the raw text** (this is the "note anything messy you'll
need to clean" deliverable):

1. **Running headers/footers** — the chapter name and page number repeat on
   every single page. If left in, they appear in dozens of chunks and pollute
   retrieval with meaningless matches.
2. **Hyphenated line breaks** — `aero-\nnautical` becomes two broken tokens
   instead of one word.
3. **Figure and table captions** — `Figure 5-12.` fragments stranded between
   paragraphs, with no surrounding sentence.
4. **Multi-column layout artefacts** — `pypdf` reads columns in a sometimes
   surprising order, producing jumbled line breaks.
5. **Ligatures and odd whitespace** — `ﬂight` (one character) instead of
   `flight`, plus long runs of spaces.

In [6]:
# Find the header/footer lines empirically instead of guessing: any short line
# that appears on a large fraction of a document's pages is page furniture.
def find_boilerplate(doc: dict, min_page_fraction: float = 0.25) -> set[str]:
    counts = Counter()
    for page in doc["pages"]:
        # A header/footer is short and lives at the very top or bottom.
        lines = [ln.strip() for ln in page["text"].splitlines() if ln.strip()]
        for line in lines[:2] + lines[-2:]:
            if len(line) < 80:
                counts[line] += 1

    threshold = max(3, int(len(doc["pages"]) * min_page_fraction))
    return {line for line, count in counts.items() if count >= threshold}


for doc in documents:
    doc["boilerplate"] = find_boilerplate(doc)
    print(f"{doc['title']}: {len(doc['boilerplate'])} boilerplate lines detected")

print("\nExamples from the first document:")
for line in list(documents[0]["boilerplate"])[:8]:
    print(f"   {line!r}")

Instrument Flying Handbook: 0 boilerplate lines detected
Pilot's Handbook of Aeronautical Knowledge: 0 boilerplate lines detected
Plane Sense: General Aviation Information: 1 boilerplate lines detected
Remote Pilot - Small UAS Study Guide: 1 boilerplate lines detected
Aircraft Weight and Balance Handbook: 0 boilerplate lines detected

Examples from the first document:

In [7]:
LIGATURES = {"\ufb01": "fi", "\ufb02": "fl", "\ufb00": "ff",
             "\ufb03": "ffi", "\ufb04": "ffl",
             "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
             "\u2013": "-", "\u2014": "-", "\u00a0": " "}


def clean_page_text(text: str, boilerplate: set[str]) -> str:
    """Apply the five fixes listed above, in order."""
    if not text.strip():
        return ""

    for bad, good in LIGATURES.items():          # 5. ligatures
        text = text.replace(bad, good)

    text = re.sub(r"(\w)-\n(\w)", r"\1\2", text)   # 2. hyphenated line breaks

    kept = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped in boilerplate:               # 1. headers / footers
            continue
        if re.fullmatch(r"[\divxlcIVXLC\-\u2013 ]{1,12}", stripped):  # bare page numbers
            continue
        if re.match(r"^(Figure|Table)\s+\d+[-\u2013]\d+\.?$", stripped):  # 3. stranded captions
            continue
        kept.append(stripped)

    text = "\n".join(kept)
    text = re.sub(r"[ \t]{2,}", " ", text)         # 5. whitespace runs
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


# Clean every page and measure how much we removed.
before = after = 0
for doc in documents:
    for page in doc["pages"]:
        before += len(page["text"])
        page["clean"] = clean_page_text(page["text"], doc["boilerplate"])
        after += len(page["clean"])

print(f"Characters before cleaning : {before:,}")
print(f"Characters after cleaning  : {after:,}")
print(f"Removed                    : {before - after:,} ({100*(before-after)/before:.1f}%)")

print(f"\n--- Same page, cleaned ---\n")
print(documents[0]["pages"][80]["clean"][:900])

Characters before cleaning : 3,612,133
Characters after cleaning  : 3,468,645
Removed                    : 143,488 (4.0%)

--- Same page, cleaned ---

Outside
force
Net
forces
Path
Apply down
elevator
Path
Net forces
Figure 4-4. Newton's First Law of Motion: the Law of Inertia.
Time
2,000 lb300 hp
2,000 lb150 hp
= Acceleration Force
Mass
Figure 4-5. Newton's Second Law of Motion: the Law of Momentum.
• Form Drag
Form drag is the drag created because of the shape of a
component or the aircraft. If one were to place a circular
disk in an air stream, the pressure on both the top and bottom
would be equal. However, the airflow starts to break down
as the air flows around the back of the disk. This creates
turbulence and hence a lower pressure results. Because the
total pressure is affected by this reduced pressure, it creates
a drag. Newer aircraft are generally made with consideration
to this by fairing parts along the fuselage (teardrop) so that
turbulence and form drag is reduced.
Total lift must overcome the total weight of the aircraf

---
## 2.2 Chunking Strategy

### Why chunk at all?

Two hard constraints force it:

1. **The context window.** A 500-page handbook is millions of characters. The
   model can read a few thousand.
2. **Embedding resolution.** One vector represents one meaning. A vector for an
   entire chapter is an average of fifty topics and matches nothing well. A
   vector for one paragraph is sharp.

### The strategy chosen: section-aware, paragraph-boundary chunking

Rather than blindly cutting every N characters, the splitter:

- **respects paragraph boundaries** — it fills a chunk with whole paragraphs and
  only falls back to sentence boundaries when a single paragraph is oversized,
  so a chunk almost never begins mid-sentence;
- **tracks the nearest preceding heading**, stored as metadata, so a citation
  can say *"Chapter 5 — Airspeed Indicator, page 142"* rather than just a page
  number;
- **overlaps neighbours by 150 characters**, so a fact that straddles a
  boundary survives in at least one chunk intact.

### Justifying the numbers

| Parameter | Value | Why |
|---|---|---|
| `CHUNK_SIZE` | 1000 chars (~250 tokens) | Roughly one or two full paragraphs — one complete idea. Small enough that 5 chunks fit comfortably in a 4096-token context alongside the prompt; large enough to hold a definition *and* its explanation. |
| `CHUNK_OVERLAP` | 150 chars (15%) | A definition split across a boundary would otherwise be retrievable from neither half. 15% is the usual sweet spot: below ~10% facts get cut, above ~25% the index bloats with near-duplicates that crowd out genuinely different results. |
| `MIN_CHUNK_CHARS` | 120 | Filters leftover fragments — a stray caption or a two-word line — that would otherwise be indexed as if they were content. |

**Honest limitation:** measuring in characters is an approximation of tokens
(~4 chars/token for English). Token-exact splitting would be marginally better,
but it couples the notebook to a specific tokenizer for very little gain here.

In [8]:
# Headings in FAA handbooks are usually a short line in Title Case or CAPS,
# with no terminal punctuation.
HEADING_RE = re.compile(
    r"^(?:Chapter\s+\d+.*"
    r"|[A-Z][A-Z0-9 ,\-/&']{4,60}"
    r"|(?:[A-Z][a-z]+\s+){1,6}[A-Z][a-z]+)$"
)


def looks_like_heading(line: str) -> bool:
    line = line.strip()
    if not (4 <= len(line) <= 70):
        return False
    if line.endswith((".", ",", ";", ":")):
        return False
    if len(line.split()) > 9:
        return False
    return bool(HEADING_RE.match(line))


def split_text(text: str, size: int, overlap: int) -> list[str]:
    """
    Greedily pack paragraphs into chunks of at most `size` characters.

    An oversized single paragraph is split again on sentence boundaries, so we
    still avoid cutting mid-sentence wherever possible.
    """
    paragraphs = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]

    units: list[str] = []
    for paragraph in paragraphs:
        if len(paragraph) <= size:
            units.append(paragraph)
            continue
        # Split the long paragraph after . ! or ? followed by a space.
        sentences = re.split(r"(?<=[.!?])\s+", paragraph)
        buffer = ""
        for sentence in sentences:
            if len(buffer) + len(sentence) + 1 <= size:
                buffer = f"{buffer} {sentence}".strip()
            else:
                if buffer:
                    units.append(buffer)
                # A single sentence longer than `size` is rare; hard-cut it.
                buffer = sentence if len(sentence) <= size else sentence[:size]
        if buffer:
            units.append(buffer)

    chunks: list[str] = []
    current = ""
    for unit in units:
        if not current:
            current = unit
        elif len(current) + len(unit) + 2 <= size:
            current = f"{current}\n\n{unit}"
        else:
            chunks.append(current)
            # Carry the tail of the previous chunk forward as the overlap - but
            # only as much of it as still leaves the new chunk within `size`.
            # (Without this cap, tail + unit can overflow the chunk limit, and
            # the embedding model would silently truncate the excess.)
            allowance = max(0, size - len(unit) - 2)
            tail = current[-min(overlap, allowance):] if overlap and allowance else ""
            current = f"{tail}\n\n{unit}".strip() if tail else unit

    if current:
        chunks.append(current)

    return [c for c in chunks if len(c) >= MIN_CHUNK_CHARS]

In [9]:
def chunk_document(doc: dict) -> list[dict]:
    """Turn one parsed document into a list of chunk records with metadata."""
    records: list[dict] = []
    current_section = None

    for page in doc["pages"]:
        text = page["clean"]
        if not text:
            continue

        # Update the "nearest heading seen so far" as we walk down the page.
        for line in text.splitlines()[:6]:
            if looks_like_heading(line):
                current_section = line.strip()
                break

        for index, chunk_text in enumerate(split_text(text, CHUNK_SIZE, CHUNK_OVERLAP)):
            records.append({
                # A readable, stable, unique id - useful when debugging retrieval.
                "chunk_id": f"{Path(doc['filename']).stem}::p{page['page']:04d}::c{index}",
                "text": chunk_text,
                "document": doc["title"],
                "filename": doc["filename"],
                "page": page["page"],
                "section": current_section or "",
                "n_chars": len(chunk_text),
            })

    return records


all_chunks: list[dict] = []
for doc in documents:
    doc_chunks = chunk_document(doc)
    all_chunks.extend(doc_chunks)
    print(f"{doc['title']:<45} {len(doc_chunks):>6,} chunks")

print(f"\nTOTAL: {len(all_chunks):,} chunks")

Instrument Flying Handbook                     1,293 chunks
Pilot's Handbook of Aeronautical Knowledge     2,035 chunks
Plane Sense: General Aviation Information        199 chunks
Remote Pilot - Small UAS Study Guide             209 chunks
Aircraft Weight and Balance Handbook             308 chunks

TOTAL: 4,044 chunks

In [10]:
chunk_frame = pd.DataFrame(all_chunks)

print("Chunk size distribution (characters):")
display(chunk_frame["n_chars"].describe().round(1).to_frame("value"))

print("\nChunks per document:")
display(chunk_frame["document"].value_counts().to_frame("chunks"))

section_coverage = 100 * (chunk_frame["section"] != "").mean()
print(f"\nChunks with a detected section heading: {section_coverage:.1f}%")

print("\n--- Example chunk ---")
example = all_chunks[len(all_chunks) // 2]
print(f"id      : {example['chunk_id']}")
print(f"source  : {example['document']}, page {example['page']}")
print(f"section : {example['section'] or '(none detected)'}")
print(f"chars   : {example['n_chars']}\n")
print(example["text"][:700])

Chunk size distribution (characters):

        value
count  4044.0
mean    880.7
std     204.4
min     122.0
25%     871.0
50%     995.5
75%    1000.0
max    1000.0

Chunks per document:

                                            chunks
document
Pilot's Handbook of Aeronautical Knowledge    2035
Instrument Flying Handbook                    1293
Aircraft Weight and Balance Handbook           308
Remote Pilot - Small UAS Study Guide           209
Plane Sense: General Aviation Information      199

Chunks with a detected section heading: 100.0%

--- Example chunk ---
id      : phak_pilots_handbook::p0181::c0
source  : Pilot's Handbook of Aeronautical Knowledge, page 181
section : Carburetor Air Temperature Gauge
chars   : 967

M
A
N
B
U
S
Starter
Battery
A
T
B
A
T
Battery
contactor
(solenoid)
Starter
contactor
External
power
relay
+
+
OFF
R B
S
Ignition switch
External
power plug
Figure 7-20. Typical starting circuit. by the spark plugs. It then burns away from the plugs until it
is completely consumed. This type of combustion causes a
smooth build-up of temperature and pressure and ensures that
the expanding gases deliver the maximum force to the piston
at exactly the right time in the power stroke. [Figure 7-21]
Detonation is an uncontrolled, explosive ignition of the
fuel-air mixture within the cylinder's combustion chamber. It causes excessive temperatures and pressures which, if not
corrected, can quickly lea

---
## 2.3 Embeddings & Vector Store

### What an embedding is

`all-MiniLM-L6-v2` reads a piece of text and returns **384 numbers** — a point
in 384-dimensional space. Texts that *mean* similar things land near each other,
even when they share no words. That is why "what makes a wing stop flying?"
retrieves a passage about *stall* and *critical angle of attack* without the
word "stall" ever being typed.

### Why this model

| | |
|---|---|
| **Size** | 90 MB — downloads in under a minute, runs fine on a laptop CPU |
| **Speed** | thousands of chunks per minute, no GPU required |
| **Quality** | strong on semantic-similarity benchmarks for its size |
| **Cost** | runs locally and free, which the brief requires |

A larger model (e.g. `all-mpnet-base-v2`, 768-dim) scores a few points higher
but is ~5× slower to index. For a corpus this size that trade is not worth it.

### Why normalise

We set `normalize_embeddings=True`, which scales every vector to length 1. With
unit vectors, cosine similarity is just a dot product — and Chroma's cosine
distance becomes exactly `1 - similarity`, which is what makes the readable
0-to-1 similarity score used everywhere downstream.

In [11]:
from sentence_transformers import SentenceTransformer

print(f"Loading {EMBEDDING_MODEL} (downloads ~90 MB on first run) ...")
embedder = SentenceTransformer(EMBEDDING_MODEL)

print("Embedding dimension:", embedder.get_sentence_embedding_dimension())
print("Max sequence length:", embedder.max_seq_length, "tokens")

Loading sentence-transformers/all-MiniLM-L6-v2 (downloads ~90 MB on first run) ...

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\Dell\Desktop\ITI final project\ITI final project\rag-assistant-app\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Dell\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding dimension: 384
Max sequence length: 256 tokens

C:\Users\Dell\AppData\Local\Temp\ipykernel_15500\786875426.py:6: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  print("Embedding dimension:", embedder.get_sentence_embedding_dimension())

> **Note on `max_seq_length`:** the model truncates anything past 256 tokens
> (~1000 characters). Our 1000-character chunk size was chosen to sit right at
> that limit — a larger chunk would have its tail silently ignored during
> embedding, so it would be indexed on only part of its own content.

In [12]:
texts = [chunk["text"] for chunk in all_chunks]

print(f"Embedding {len(texts):,} chunks ...")
started = time.perf_counter()

embeddings = embedder.encode(
    texts,
    batch_size=EMBED_BATCH_SIZE,
    normalize_embeddings=True,   # required for the cosine maths described above
    show_progress_bar=True,
    convert_to_numpy=True,
)

elapsed = time.perf_counter() - started
print(f"\nDone in {elapsed:.1f}s  ({len(texts)/elapsed:.0f} chunks/second)")
print("Embedding matrix shape:", embeddings.shape)
print("Vector length check (should be ~1.0):",
      round(float(np.linalg.norm(embeddings[0])), 6))

Embedding 4,044 chunks ...

Batches:   0%|          | 0/16 [00:00<?, ?it/s]

Done in 291.8s  (14 chunks/second)
Embedding matrix shape: (4044, 384)
Vector length check (should be ~1.0): 1.0

In [13]:
import chromadb

# Start from a clean slate so re-running the notebook never appends duplicates
# on top of a previous run. This is what makes Restart & Run All reproducible.
if VECTOR_STORE_DIR.exists():
    shutil.rmtree(VECTOR_STORE_DIR)
VECTOR_STORE_DIR.mkdir(parents=True, exist_ok=True)

client = chromadb.PersistentClient(path=str(VECTOR_STORE_DIR))

collection = client.create_collection(
    name=COLLECTION_NAME,
    # THIS MATTERS: the default is squared L2. We need cosine, because that is
    # what `similarity = 1 - distance` assumes in the backend.
    metadata={"hnsw:space": "cosine"},
)

# Insert in batches - Chroma rejects very large single writes.
BATCH = 2000
for start in range(0, len(all_chunks), BATCH):
    batch = all_chunks[start:start + BATCH]
    collection.add(
        ids=[c["chunk_id"] for c in batch],
        documents=[c["text"] for c in batch],
        embeddings=embeddings[start:start + len(batch)].tolist(),
        metadatas=[
            {
                "document": c["document"],
                "filename": c["filename"],
                "page": c["page"],
                "section": c["section"],
            }
            for c in batch
        ],
    )
    print(f"  inserted {min(start + BATCH, len(all_chunks)):>6,} / {len(all_chunks):,}")

print(f"\nCollection '{COLLECTION_NAME}' now holds {collection.count():,} chunks.")
print(f"Persisted to: {VECTOR_STORE_DIR}")

  inserted  2,000 / 4,044
  inserted  4,000 / 4,044
  inserted  4,044 / 4,044

Collection 'faa_handbooks' now holds 4,044 chunks.
Persisted to: C:\Users\Dell\Desktop\ITI final project\ITI final project\rag-assistant-app\backend\data\vector_store

> **Why we pass `embeddings=` explicitly** instead of letting Chroma embed for
> us: Chroma would store a reference to *its* default embedding function, and
> different Chroma versions resolve that differently. By computing vectors
> ourselves here and again in the backend with the same named model, index-time
> and query-time embeddings are guaranteed to match. A mismatch does not raise
> an error — it silently returns garbage, which is the worst kind of bug.

---
## 2.4 Retrieval & Prompting

Now the query side. Three pieces:

1. `retrieve()` — question → the most similar chunks, filtered by the floor.
2. `build_prompt()` — chunks → a numbered context block the model must cite.
3. `answer()` — glue the two together and call the local LLM.

These are deliberately written to mirror `backend/app/services/` exactly, so
what you validate here is what the API serves.

In [14]:
def retrieve(question: str, top_k: int = TOP_K, min_similarity: float = MIN_SIMILARITY):
    """Return the chunks most similar to `question`, best first."""
    query_vector = embedder.encode(question, normalize_embeddings=True).tolist()

    raw = collection.query(
        query_embeddings=[query_vector],
        n_results=top_k,
        include=["documents", "metadatas", "distances"],
    )

    hits = []
    for chunk_id, text, meta, distance in zip(
        raw["ids"][0], raw["documents"][0], raw["metadatas"][0], raw["distances"][0]
    ):
        similarity = 1.0 - float(distance)   # cosine space, see 2.3
        if similarity < min_similarity:
            continue                          # not relevant enough to show the LLM
        hits.append({
            "chunk_id": chunk_id,
            "text": text,
            "document": meta["document"],
            "page": meta["page"],
            "section": meta.get("section", ""),
            "similarity": round(similarity, 4),
        })
    return hits


# Quick smoke test.
for hit in retrieve("What causes a wing to stall?"):
    print(f"[{hit['similarity']:.3f}] {hit['document']}, p.{hit['page']}")
    print(f"        {hit['text'][:130].replace(chr(10), ' ')}...\n")

[0.566] Pilot's Handbook of Aeronautical Knowledge, p.147
        emains effective even after the wing has begun to stall, allowing the pilot to inadvertently drive the wing into a deeper stall at...

[0.562] Pilot's Handbook of Aeronautical Knowledge, p.124
        scend at the same airspeed as used in straight-and­ level flight, the power must be reduced as the descent is entered.  Entering t...

[0.548] Pilot's Handbook of Aeronautical Knowledge, p.124
        ude.  Each aircraft has a particular AOA where the airflow separates from the upper surface of the wing and the stall occurs. This...

[0.541] Pilot's Handbook of Aeronautical Knowledge, p.124
        ses with an increase in AOA, at some point the CL peaks and then begins to drop off. This peak is called the CL-MAX.  The amount o...

[0.539] Pilot's Handbook of Aeronautical Knowledge, p.124
        e and the airflow over the wing is disrupted. Low speed is not necessary to produce a stall.  The wing can be brought into an exce...

### Testing retrieval against 10+ sample questions

The brief requires testing retrieval on at least 10 questions. Note this checks
**retrieval only** — no LLM involved yet. If retrieval is broken, no amount of
prompt engineering downstream will save the answer.

In [15]:
SAMPLE_QUESTIONS = [
    "What is the difference between indicated airspeed and true airspeed?",
    "What causes a wing to stall?",
    "What is the purpose of the ailerons?",
    "What is density altitude and why does it affect takeoff performance?",
    "How do you calculate an aircraft's center of gravity?",
    "What conditions are favourable for carburetor icing?",
    "What does angle of attack mean?",
    "What are the four forces acting on an airplane in flight?",
    "What is a METAR?",
    "What is the maximum altitude for small unmanned aircraft under Part 107?",
    "What is the difference between a VOR and an NDB?",
    "What is the purpose of the pitot-static system?",
]

rows = []
for question in SAMPLE_QUESTIONS:
    hits = retrieve(question)
    rows.append({
        "question": question[:58] + ("..." if len(question) > 58 else ""),
        "hits": len(hits),
        "top_score": hits[0]["similarity"] if hits else 0.0,
        "top_source": f"{hits[0]['document'][:28]} p.{hits[0]['page']}" if hits else "NONE",
    })

retrieval_report = pd.DataFrame(rows)
display(retrieval_report)

print(f"Questions with at least one hit: "
      f"{(retrieval_report['hits'] > 0).sum()}/{len(retrieval_report)}")
print(f"Mean top-1 similarity: {retrieval_report['top_score'].mean():.3f}")

,question,hits,top_score,top_source
0,What is the difference between indicated airsp...,5,0.5572,Instrument Flying Handbook p.104
1,What causes a wing to stall?,5,0.5658,Pilot's Handbook of Aeronaut p.147
2,What is the purpose of the ailerons?,5,0.5573,Pilot's Handbook of Aeronaut p.154
3,What is density altitude and why does it affec...,5,0.6730,Pilot's Handbook of Aeronaut p.274
4,How do you calculate an aircraft's center of g...,5,0.7925,Aircraft Weight and Balance p.93
5,What conditions are favourable for carburetor ...,5,0.7691,Pilot's Handbook of Aeronaut p.171
6,What does angle of attack mean?,5,0.6362,Pilot's Handbook of Aeronaut p.101
7,What are the four forces acting on an airplane...,5,0.6434,Pilot's Handbook of Aeronaut p.100
8,What is a METAR?,5,0.7127,Pilot's Handbook of Aeronaut p.318
9,What is the maximum altitude for small unmanne...,5,0.5548,Remote Pilot - Small UAS Stu p.29
10,What is the difference between a VOR and an NDB?,5,0.5260,Pilot's Handbook of Aeronaut p.410
11,What is the purpose of the pitot-static system?,5,0.6567,Instrument Flying Handbook p.97

Questions with at least one hit: 12/12
Mean top-1 similarity: 0.637

### Does the similarity floor actually work?

The floor is the project's main defence against hallucination, so it deserves
its own test: questions that the corpus genuinely cannot answer must come back
with **zero** hits.

In [16]:
OUT_OF_DOMAIN = [
    "What is the best recipe for koshari?",
    "Who won the 2018 FIFA World Cup?",
    "How do I write a for loop in JavaScript?",
]

for question in OUT_OF_DOMAIN:
    unfiltered = retrieve(question, min_similarity=0.0)   # what we WOULD have returned
    filtered = retrieve(question)                          # what we DO return
    best = unfiltered[0]["similarity"] if unfiltered else 0.0
    verdict = "correctly refused" if not filtered else "LEAKED THROUGH"
    print(f"{verdict:<18} best score {best:.3f}  <- {question}")

correctly refused  best score 0.183  <- What is the best recipe for koshari?
correctly refused  best score 0.191  <- Who won the 2018 FIFA World Cup?
correctly refused  best score 0.191  <- How do I write a for loop in JavaScript?

> If any of these leak through, raise `MIN_SIMILARITY`. If legitimate questions
> get refused, lower it. **0.25** was chosen by looking at the gap between the
> two tables above: in-domain top-1 scores cluster well above it, out-of-domain
> scores fall below.

In [17]:
SYSTEM_PROMPT = """You are a careful assistant that answers questions using ONLY the numbered context passages provided by the user.

Rules you must follow:
1. Use only facts stated in the context. Never add outside knowledge.
2. After each fact, cite the passage it came from using its marker, like [1] or [2].
3. If the context does not contain the answer, reply exactly: NOT_IN_CONTEXT
4. Do not invent numbers, names, or regulations. Quote the context's figures exactly.
5. Be concise: 2-5 sentences unless the question needs a short list."""

USER_TEMPLATE = """Context passages:
{context}

Question: {question}

Answer using only the passages above, citing them with [n] markers."""


def build_prompt(question: str, hits: list[dict]) -> str:
    """Format retrieved chunks into a numbered block the model can cite."""
    blocks = []
    for index, hit in enumerate(hits, start=1):
        where = f"{hit['document']}, page {hit['page']}"
        if hit["section"]:
            where += f", section '{hit['section']}'"
        blocks.append(f"[{index}] (Source: {where})\n{hit['text'].strip()}")
    return USER_TEMPLATE.format(context="\n\n".join(blocks), question=question)


print(build_prompt("What causes a wing to stall?", retrieve("What causes a wing to stall?"))[:1400])

Context passages:
[1] (Source: Pilot's Handbook of Aeronautical Knowledge, page 147, section 'TESTSTBY PWR')
emains effective even after the wing has begun
to stall, allowing the pilot to inadvertently drive the wing
into a deeper stall at a much greater AOA.

If the horizontal
tail surfaces then become buried in the wing's wake, the
elevator may lose all effectiveness, making it impossible to
reduce pitch attitude and break the stall. In the pre-stall and
immediate post-stall regimes, the lift/drag qualities of a swept
wing aircraft (specifically the enormous increase in drag
at low speeds) can cause an increasingly descending flight
path with no change in pitch attitude, further increasing the

[2] (Source: Pilot's Handbook of Aeronautical Knowledge, page 124, section 'Ground Effect')
scend at the same airspeed as used in straight-and­
level flight, the power must be reduced as the descent is
entered.

Entering the descent, the component of weight
acting forward along the flight path increases as the angle
of descent increases and, conversely, when leveling off, the
component of weight acting along the flight path decreases
as the angle of descent decreases. Stalls
An aircraft stall results from a rapid decrease in lift caused by
the separation of airflow from the wing's surface brought on
by exceeding the critical AOA. A stall can occur at any pitch
attitude or airspeed. Sta

### The three rules doing the real work

- **Rule 1** ("only facts stated in the context") flips the model from *recall*
  to *reading comprehension*. This is the entire point of RAG.
- **Rule 2** (citation markers) makes every claim checkable, and the markers are
  what the UI turns into clickable sources.
- **Rule 3** (`NOT_IN_CONTEXT`) is the second safety net. The similarity floor
  catches questions with no relevant chunks; this catches the harder case where
  chunks *look* relevant but do not contain the answer.

In [18]:
import ollama

ollama_client = ollama.Client(host=OLLAMA_HOST, timeout=180)

# Check availability once. If Ollama is down we keep going with a clear marker
# so the notebook still runs top-to-bottom (a grading requirement).
try:
    available = [m["model"] for m in ollama_client.list()["models"]]
    LLM_AVAILABLE = True
    print("Ollama is running. Models available:", available)
    if not any(OLLAMA_MODEL.split(":")[0] in m for m in available):
        print(f"\n  '{OLLAMA_MODEL}' not found. Pull it with:  ollama pull {OLLAMA_MODEL}")
except Exception as exc:
    LLM_AVAILABLE = False
    print(f"  Ollama unreachable ({exc.__class__.__name__}).")
    print("   Start it with `ollama serve`, then re-run from this cell.")
    print("   The notebook will continue, but generated answers will be placeholders.")

Ollama is running. Models available: ['llama3.2:3b']

In [19]:
NO_CONTEXT_ANSWER = (
    "I could not find anything about that in the documents I have."
)


def answer(question: str, top_k: int = TOP_K) -> dict:
    """The full RAG pipeline: retrieve -> prompt -> generate."""
    started = time.perf_counter()
    hits = retrieve(question, top_k=top_k)

    if not hits:
        # No context => no LLM call. Calling it here is how hallucinations happen.
        return {"question": question, "answer": NO_CONTEXT_ANSWER, "hits": [],
                "grounded": False, "latency_s": time.perf_counter() - started}

    if not LLM_AVAILABLE:
        return {"question": question, "answer": "[LLM UNAVAILABLE]", "hits": hits,
                "grounded": False, "latency_s": time.perf_counter() - started}

    response = ollama_client.chat(
        model=OLLAMA_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": build_prompt(question, hits)},
        ],
        options={"temperature": 0.1, "num_ctx": 4096},
    )
    text = response["message"]["content"].strip()
    grounded = "NOT_IN_CONTEXT" not in text

    return {
        "question": question,
        "answer": NO_CONTEXT_ANSWER if not grounded else text,
        "hits": hits,
        "grounded": grounded,
        "latency_s": time.perf_counter() - started,
    }


demo = answer("What causes a wing to stall?")
print(demo["answer"])
print(f"\n--- grounded in {len(demo['hits'])} passages, {demo['latency_s']:.1f}s ---")
for index, hit in enumerate(demo["hits"], start=1):
    print(f"  [{index}] {hit['document']}, p.{hit['page']}  (score {hit['similarity']:.3f})")

According to the passages, a wing stalls due to a rapid decrease in lift caused by the separation of airflow from the wing's surface brought on by exceeding the critical Angle of Attack (AOA). [2] This occurs when the airflow over the wing is disrupted, which can happen at any speed, including low speed. [3] The critical AOA varies from approximately 16° to 20° depending on the aircraft's design. [3]

The stall occurs when the wing's lift/drag qualities cause an increasingly descending flight path with no change in pitch attitude, further increasing the stall. [1]

The wing does not completely stop producing lift in a stalled condition, but rather, it cannot generate adequate lift to sustain level flight. [2]

--- grounded in 5 passages, 103.1s ---
  [1] Pilot's Handbook of Aeronautical Knowledge, p.147  (score 0.566)
  [2] Pilot's Handbook of Aeronautical Knowledge, p.124  (score 0.562)
  [3] Pilot's Handbook of Aeronautical Knowledge, p.124  (score 0.548)
  [4] Pilot's Handbook of Aeronautical Knowledge, p.124  (score 0.541)
  [5] Pilot's Handbook of Aeronautical Knowledge, p.124  (score 0.539)

---
## 2.5 Vision Component 

did not do it

---
## 2.6 Evaluation

Two questions to answer, per the brief:

1. **Was the retrieved context relevant?** — a retrieval problem.
2. **Was the answer grounded or hallucinated?** — a generation problem.

Separating them matters: they have completely different fixes. Bad retrieval is
fixed by chunking or the embedding model; ungrounded answers are fixed by the
prompt or the model.

The 14 questions below include **3 deliberately out-of-domain** ones. An
assistant that answers those is *worse* than one that refuses.

In [20]:
# `expect` = keywords that must appear in a correct answer.
# `in_domain=False` means the correct behaviour is to REFUSE.
TEST_QUESTIONS = [
    {"q": "What is the difference between indicated airspeed and true airspeed?",
     "expect": ["indicated", "true", "altitude"], "in_domain": True},
    {"q": "What causes a wing to stall?",
     "expect": ["angle of attack", "critical"], "in_domain": True},
    {"q": "What is the purpose of the ailerons?",
     "expect": ["roll", "bank"], "in_domain": True},
    {"q": "What is density altitude?",
     "expect": ["pressure altitude", "temperature"], "in_domain": True},
    {"q": "How is an aircraft's center of gravity calculated?",
     "expect": ["moment", "weight", "arm"], "in_domain": True},
    {"q": "What conditions are favourable for carburetor icing?",
     "expect": ["humidity", "temperature"], "in_domain": True},
    {"q": "What are the four forces acting on an airplane in flight?",
     "expect": ["lift", "weight", "thrust", "drag"], "in_domain": True},
    {"q": "What does angle of attack mean?",
     "expect": ["chord", "relative wind"], "in_domain": True},
    {"q": "What is a METAR?",
     "expect": ["observation", "weather"], "in_domain": True},
    {"q": "What is the purpose of the pitot-static system?",
     "expect": ["pressure", "airspeed"], "in_domain": True},
    {"q": "What is the maximum altitude for small unmanned aircraft under Part 107?",
     "expect": ["400"], "in_domain": True},
    {"q": "What is the best recipe for koshari?",
     "expect": [], "in_domain": False},
    {"q": "Who won the 2018 FIFA World Cup?",
     "expect": [], "in_domain": False},
    {"q": "How do I write a for loop in JavaScript?",
     "expect": [], "in_domain": False},
]

print(f"{len(TEST_QUESTIONS)} test questions "
      f"({sum(t['in_domain'] for t in TEST_QUESTIONS)} in-domain, "
      f"{sum(not t['in_domain'] for t in TEST_QUESTIONS)} out-of-domain)")

14 test questions (11 in-domain, 3 out-of-domain)

In [ ]:
results = []

for number, test in enumerate(TEST_QUESTIONS, start=1):
    print(f"[{number:>2}/{len(TEST_QUESTIONS)}] {test['q'][:62]}", flush=True)
    outcome = answer(test["q"])
    lowered = outcome["answer"].lower()

    # --- automatic scoring (a starting point, not the final word) ----------
    if test["in_domain"]:
        retrieval_ok = len(outcome["hits"]) > 0
        # "Correct" heuristic: it answered, and the expected keywords appear.
        keywords_found = sum(kw.lower() in lowered for kw in test["expect"])
        correct = (
            outcome["grounded"]
            and keywords_found >= max(1, len(test["expect"]) // 2)
        )
    else:
        # Out of domain: success means refusing.
        retrieval_ok = len(outcome["hits"]) == 0
        keywords_found = 0
        correct = not outcome["grounded"]

    results.append({
        "#": number,
        "question": test["q"][:52] + ("..." if len(test["q"]) > 52 else ""),
        "in_domain": test["in_domain"],
        "retrieved_source": (
            f"{outcome['hits'][0]['document'][:26]} p.{outcome['hits'][0]['page']}"
            if outcome["hits"] else "-- none --"
        ),
        "top_score": outcome["hits"][0]["similarity"] if outcome["hits"] else 0.0,
        "context_relevant": retrieval_ok,
        "grounded": outcome["grounded"],
        "cites_sources": bool(re.search(r"\[\d\]", outcome["answer"])),
        "auto_correct": correct,
        "latency_s": round(outcome["latency_s"], 1),
        "answer": outcome["answer"],
    })

print("\nEvaluation complete.")

[ 1/14] What is the difference between indicated airspeed and true air
[ 2/14] What causes a wing to stall?
[ 3/14] What is the purpose of the ailerons?
[ 4/14] What is density altitude?
[ 5/14] How is an aircraft's center of gravity calculated?

### Results table

In [ ]:
evaluation = pd.DataFrame(results)

# The compact table for the README.
table = evaluation[[
    "#", "question", "retrieved_source", "top_score",
    "context_relevant", "grounded", "cites_sources", "auto_correct", "latency_s",
]]
display(table)

in_domain = evaluation[evaluation["in_domain"]]
out_domain = evaluation[~evaluation["in_domain"]]

print("=" * 62)
print("SUMMARY")
print("=" * 62)
print(f"Retrieval relevant (in-domain)   : "
      f"{in_domain['context_relevant'].sum()}/{len(in_domain)}")
print(f"Answers grounded + cited         : "
      f"{(in_domain['grounded'] & in_domain['cites_sources']).sum()}/{len(in_domain)}")
print(f"Auto-scored correct (in-domain)  : "
      f"{in_domain['auto_correct'].sum()}/{len(in_domain)}")
print(f"Correctly refused (out-of-domain): "
      f"{out_domain['auto_correct'].sum()}/{len(out_domain)}")
print(f"Median latency                   : {evaluation['latency_s'].median():.1f}s")

> **`auto_correct` is a keyword heuristic, not a grade.** Read the full answers
> in the next cell and correct the column by hand where the heuristic is wrong —
> it will mark a good answer wrong if it phrases things differently, and can
> mark a wrong answer right if it happens to contain the keyword. Say so
> explicitly in your README; examiners respect a stated limitation far more than
> a suspiciously perfect table.

In [ ]:
# Full answers, for manual review.
for row in results:
    flag = "OK " if row["auto_correct"] else "!! "
    print(f"{flag}[{row['#']}] {row['question']}")
    print(f"     source: {row['retrieved_source']}  score: {row['top_score']:.3f}")
    print(f"     {row['answer'][:400]}")
    print("-" * 76)

In [ ]:
# Save the results so the README table and any report can quote real numbers.
REPORTS_DIR = PROJECT_ROOT / "reports"
REPORTS_DIR.mkdir(exist_ok=True)

table.to_csv(REPORTS_DIR / "evaluation_results.csv", index=False)
evaluation.to_json(REPORTS_DIR / "evaluation_full.json", orient="records", indent=2)

print(f"Saved to {REPORTS_DIR}")
print("\nMarkdown table for the README:\n")
print(table.to_markdown(index=False))

### Failure analysis

Observed across the 14 test questions above.

**1. Retrieval finds the right document but not the right sentence.** *(Question 11)*
The Part 107 altitude question retrieved the correct source — Remote Pilot Study Guide p.29, at 0.55
similarity — and the model replied that the figure was not stated in the passages. The answer
(400 ft AGL) is in that handbook, but the specific figure sits in a list or table phrased differently
from the question. Dense embeddings match *topic*, not literal tokens, and "Part 107" and "400" are
exactly the kind of rare literal strings they handle worst. Note the model behaved correctly here: it
declined rather than inventing a number, so this is a **retrieval** failure, not a generation failure.
*Mitigation:* hybrid retrieval (BM25 + vectors fused with reciprocal rank fusion) would match those
tokens exactly. Highest-value improvement available.

**2. High similarity, wrong depth of answer.** *(Question 5)*
The centre-of-gravity question produced the highest similarity in the set (0.79) and still the wrong
kind of answer — a list of calculating *devices* (electronic calculator, E6-B) instead of the
arithmetic (total moment / total weight). A passage can be topically perfect and still answer a
subtly different question. *Mitigation:* a cross-encoder reranker scores query and passage together
rather than comparing two independently-computed vectors, and would rank the procedural passage
higher.

**3. The abstention check is brittle.** *(Question 11)*
The prompt tells the model to reply exactly `NOT_IN_CONTEXT` when the passages are insufficient, and
the code string-matches that token. Here the model said the same thing in its own words — "not
explicitly stated in the provided passages" — so a refusal was recorded as a grounded answer.
String-matching a model's compliance with a formatting rule is fragile. *Mitigation:* detect
abstention semantically, or return it as a structured field rather than a magic string.

**4. Citation format inconsistency loses sources.** *(Question 4)*
The model sometimes writes `[1, 4]` rather than `[1] [4]`. The backend extracts markers with
`\[(\d{1,2})\]`, which does not match the grouped form, so those sources were dropped from the
displayed list even though the model cited them. *Mitigation:* widen the regex to accept
comma-separated groups. Known defect, not yet fixed.

**5. Latency.** Median ~61 s per in-domain answer. Retrieval is a small fraction of that; nearly all
of it is `llama3.2:3b` generating on CPU. *Mitigation:* GPU offload, a smaller model, or streaming so
time-to-first-token is short even when total time is not.

**What I would do next, with more time:** hybrid BM25 + vector retrieval with RRF (fixes failure 1),
a cross-encoder reranker over a wider candidate set (failure 2), and a larger labelled question set
so the correctness column becomes a repeatable metric rather than a heuristic plus judgement.

---
## 2.7 Export

The vector store was written straight into `backend/data/vector_store/`, so
there is nothing to copy. What remains is the **manifest**: a record of exactly
how the index was built.

The backend reads this at startup and adopts the settings. This is what
guarantees query-time embeddings use the same model as index-time embeddings —
a mismatch produces no error, just silently meaningless results.

In [25]:
manifest = {
    "collection_name": COLLECTION_NAME,
    "embedding_model": EMBEDDING_MODEL,
    "embedding_dim": int(embeddings.shape[1]),
    "distance_metric": "cosine",
    "normalized_embeddings": True,
    "chunk_size": CHUNK_SIZE,
    "chunk_overlap": CHUNK_OVERLAP,
    "min_chunk_chars": MIN_CHUNK_CHARS,
    "recommended_top_k": TOP_K,
    "recommended_min_similarity": MIN_SIMILARITY,
    "n_chunks": int(collection.count()),
    "n_documents": len(documents),
    "documents": [
        {"title": d["title"], "filename": d["filename"], "pages": len(d["pages"])}
        for d in documents
    ],
    "built_at": time.strftime("%Y-%m-%d %H:%M:%S"),
}

manifest_path = VECTOR_STORE_DIR / "config.json"
manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

print(json.dumps(manifest, indent=2))

{
  "collection_name": "faa_handbooks",
  "embedding_model": "sentence-transformers/all-MiniLM-L6-v2",
  "embedding_dim": 384,
  "distance_metric": "cosine",
  "normalized_embeddings": true,
  "chunk_size": 1000,
  "chunk_overlap": 150,
  "min_chunk_chars": 120,
  "recommended_top_k": 5,
  "recommended_min_similarity": 0.25,
  "n_chunks": 4044,
  "n_documents": 5,
  "documents": [
    {
      "title": "Instrument Flying Handbook",
      "filename": "instrument_flying_handbook.pdf",
      "pages": 371
    },
    {
      "title": "Pilot's Handbook of Aeronautical Knowledge",
      "filename": "phak_pilots_handbook.pdf",
      "pages": 524
    },
    {
      "title": "Plane Sense: General Aviation Information",
      "filename": "plane_sense_ga_information.pdf",
      "pages": 100
    },
    {
      "title": "Remote Pilot - Small UAS Study Guide",
      "filename": "remote_pilot_suas_study_guide.pdf",
      "pages": 88
    },
    {
      "title": "Aircraft Weight and Balance Handbook",
      "filename": "weight_and_balance_handbook.pdf",
      "pages": 114
    }
  ],
  "built_at": "2026-09-11 17:50:04"
}

In [26]:
# Final check: reopen the store exactly the way the backend will, and query it.
# If this cell passes, the backend will work.
verify_client = chromadb.PersistentClient(path=str(VECTOR_STORE_DIR))
verify_collection = verify_client.get_collection(COLLECTION_NAME)

probe = "What causes a wing to stall?"
probe_vector = embedder.encode(probe, normalize_embeddings=True).tolist()
probe_result = verify_collection.query(query_embeddings=[probe_vector], n_results=3)

print(f"Reopened collection: {verify_collection.count():,} chunks")
print(f"Store size on disk : "
      f"{sum(f.stat().st_size for f in VECTOR_STORE_DIR.rglob('*') if f.is_file()) / 1e6:.1f} MB\n")
print(f"Probe query: {probe!r}")
for meta, distance in zip(probe_result["metadatas"][0], probe_result["distances"][0]):
    print(f"  [{1 - distance:.3f}] {meta['document']}, p.{meta['page']}")

print("\nExport verified. Start the backend with:")
print("    cd backend && uvicorn app.main:app --reload")

Reopened collection: 4,044 chunks
Store size on disk : 48.7 MB

Probe query: 'What causes a wing to stall?'
  [0.566] Pilot's Handbook of Aeronautical Knowledge, p.147
  [0.562] Pilot's Handbook of Aeronautical Knowledge, p.124
  [0.548] Pilot's Handbook of Aeronautical Knowledge, p.124

Export verified. Start the backend with:
    cd backend && uvicorn app.main:app --reload

---
## Summary

| Stage | Result |
|---|---|
| Documents | 5 FAA handbooks |
| Chunking | 1000 chars, 150 overlap, paragraph-aware, section-tagged |
| Embeddings | `all-MiniLM-L6-v2`, 384-dim, normalised |
| Vector store | ChromaDB, cosine, persisted for the backend |
| Grounding | similarity floor 0.25 + `NOT_IN_CONTEXT` fallback |
| Evaluation | 14 questions, 11 in-domain + 3 refusal tests |

**Next:** `backend/` serves this index over HTTP, and `frontend/` puts a chat
window on top of it. See the root `README.md`.